# Generated by Django 3.1.2 on 2020-11-16 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('allegry_info', models.CharField(default='', max_length=50)),
                ('type', models.CharField(blank=True, choices=[('ba', 'bagel'), ('be', 'beverage'), ('sc', 'Schmear'), ('sa', 'sandwich')], default='ba', help_text='Item type', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('member_number', models.CharField(default='', max_length=50)),
                ('account_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('pickup_time', models.DateTimeField(verbose_name='pickUpTime')),
                ('items', models.CharField(default='[]', max_length=1000000)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_prepared', models.BooleanField()),
                ('is_fufilled', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bagels.profile')),
            ],
        ),
    ]
